import { ICreativeBrief } from "../../models/CreativeBrief";
import { ImageGenerationResult } from "./providers/imageProvider.interface";
import { VideoGenerationResult } from "./providers/videoProvider.interface";
import { MotionGraphicScene, BrandValidationResult } from "./contentStudio.types";

/**
 * Lightweight, deterministic brand-guideline validation - no computer
 * vision, no extra LLM call. Checks what can actually be checked from
 * structured data already on hand (the brief's text, the brief's own
 * visual direction, the provider result's metadata). Never blocks a
 * generation from completing: a failed validation surfaces issues on the
 * CreativeAsset for a human to review, per the spec's "approval stays a
 * human/future action" rule.
 */

function containsForbiddenClaim(text: string, forbiddenClaims: string[]): string[] {
  const lower = text.toLowerCase();
  return forbiddenClaims.filter((claim) => claim.trim().length > 0 && lower.includes(claim.toLowerCase()));
}

function scoreFrom(issueCount: number): number {
  return Math.max(0, 100 - issueCount * 25);
}

/** TEXT validation: brand tone/forbidden-claims/CTA alignment on the brief's own copy. */
export function validateBriefText(brief: ICreativeBrief): BrandValidationResult {
  const issues: string[] = [];
  const suggestions: string[] = [];

  const fullText = [brief.hook, brief.coreMessage, ...brief.keyPoints, brief.cta].join(" ");
  const forbiddenHits = containsForbiddenClaim(fullText, brief.brandContext.forbiddenClaims);
  if (forbiddenHits.length > 0) {
    issues.push(`Copy references forbidden claim(s): ${forbiddenHits.join(", ")}`);
  }

  if (!brief.cta || brief.cta.trim().length === 0) {
    issues.push("No CTA present on the brief.");
  }

  if (!brief.toneOfVoice) {
    suggestions.push("No toneOfVoice was set - falling back to default professional B2B tone.");
  }

  return { passed: issues.length === 0, score: scoreFrom(issues.length), issues, suggestions };
}

/** GRAPHIC validation: visual direction metadata, aspect ratio, and being explicit about mock output. */
export function validateGraphicAsset(brief: ICreativeBrief, result: ImageGenerationResult): BrandValidationResult {
  const issues: string[] = [];
  const suggestions: string[] = [];

  if (result.width && result.height) {
    const [w, h] = brief.visualDirection.aspectRatio.split(":").map(Number);
    const expectedRatio = w / h;
    const actualRatio = result.width / result.height;
    if (Math.abs(expectedRatio - actualRatio) > 0.05) {
      issues.push(
        `Generated image aspect ratio (${result.width}x${result.height}) does not match required ${brief.visualDirection.aspectRatio}.`
      );
    }
  }

  if (!brief.visualDirection.colorGuidance) {
    suggestions.push("No brand color guidance was available for this brief.");
  }

  if (result.isMock) {
    suggestions.push("Generated by a development/mock provider - not a production-ready creative asset.");
  }

  return { passed: issues.length === 0, score: scoreFrom(issues.length), issues, suggestions };
}

/** VIDEO validation: messaging/CTA coverage across the scene plan, aspect ratio, and being explicit about mock output. */
export function validateVideoAsset(
  brief: ICreativeBrief,
  scenes: MotionGraphicScene[],
  result: VideoGenerationResult
): BrandValidationResult {
  const issues: string[] = [];
  const suggestions: string[] = [];

  const sceneText = scenes.map((scene) => `${scene.narration ?? ""} ${scene.onScreenText ?? ""}`).join(" ").toLowerCase();
  if (!sceneText.includes(brief.cta.toLowerCase().slice(0, 20))) {
    issues.push("No scene clearly carries the brief's CTA.");
  }

  const forbiddenHits = containsForbiddenClaim(sceneText, brief.brandContext.forbiddenClaims);
  if (forbiddenHits.length > 0) {
    issues.push(`Scene copy references forbidden claim(s): ${forbiddenHits.join(", ")}`);
  }

  if (result.isMock) {
    suggestions.push("Generated by a development/mock provider - this is a scene manifest, not a rendered video.");
  }

  return { passed: issues.length === 0, score: scoreFrom(issues.length), issues, suggestions };
}
